name: life_organizer_app
description: A comprehensive personal life organizer app for expense tracking, task management, and goal planning.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^12.1.3
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  
  # Charts & Visualization
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.41
  
  # Date & Time
  intl: ^0.19.0
  table_calendar: ^3.0.9
  
  # File Handling
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # Utils
  uuid: ^4.2.1
  logger: ^2.0.2+1
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.1

  # App Icon Generation
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Assets will be added when needed
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Custom fonts will be added when font files are available
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
